const _ = 'prevent imports and comments from collapsing';
_;
_;
_;
_;
_;
_;
_;
_;
_;
_;
_;
import { fromZodError } from 'zod-validation-error';
_;
_;
import { z } from 'zod';
const zValidVariants = z.enum(['primary', 'secondary', 'success', 'warning', 'danger', 'info', 'light', 'dark', 'outline-dark']);
const zValidNpmCommand = z.enum(['gitPush', 'publish', 'transpile']);
_, fromZodError, zValidVariants, };
