const _ = 'prevent imports and comments from collapsing';
_;
import fs from 'fs';
_;
import eris from 'eris';
_;
import path from 'path';
_;
import http from 'http';
_;
import chalk from 'chalk';
_;
import express from 'express';
_;
import fetch from 'node-fetch';
_;
import getReadLine from 'readline';
_;
import { exec, execSync } from 'child_process';
_;
import mongodb, { MongoClient } from 'mongodb';
_;
import { z } from 'zod';
_;
import { fromZodError } from 'zod-validation-error';
const zValidVariants = z.enum(['primary', 'secondary', 'success', 'warning', 'danger', 'info', 'light', 'dark', 'outline-dark']);
const zValidNpmCommand = z.enum(['gitPush', 'publish', 'transpile']);
const zValidVersionIncrement = z.enum(['major', 'minor', 'patch']);
export { _, chalk, eris, exec, execSync, express, fetch, fromZodError, fs, getReadLine, http, mongodb, MongoClient, path, z, zValidNpmCommand, zValidVariants, zValidVersionIncrement };
