import { timer } from './types.js';
export declare const GITIGNORE = "./.gitignore";
export declare const CLIENT_SRC = "./client/src";
export declare const TYPES_Z_TS = "./types/z.ts";
export declare const TYPES_IO_TS = "./types/io.ts";
export declare const ESLINT_CJS = "./.eslintrc.cjs";
export declare const GLOBAL_FNS_TS = "./global/fns.ts";
export declare const SERVER_REF_TS = "./server/ref.ts";
export declare const TSCONFIG_JSON = "./tsconfig.json";
export declare const PACKAGE_DOT_JSON = "package.json";
export declare const GLOBAL_VARS_TS = "./global/vars.ts";
export declare const SERVER_EVENTS_TS = "./server/events.ts";
export declare const CLIENT_SRC_SOCKET: string;
export declare const TSC_FLAGS = "--target esnext";
export declare const utilsRepoName = "Utils \uD83D\uDEE0\uFE0F";
export declare const isNode: boolean;
export declare const getUniqueId_generator: Generator<string | number, never, unknown>;
export declare const zValidVariants: any;
export declare const npmVersionOptions: readonly ["major", "minor", "patch"];
export declare const timers: timer[];
export declare const zMyEnv: any;
